### ISSUE TITLE
 Spark DataFrame wrapper `from_files` alternative constructor

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#106]
A `from_files` alternative constructor that uses [`pyspark_vector_files`](https://defra-data-science-centre-of-excellence.github.io/pyspark-vector-files/) to read one or more vector files into a Spark DataFrame.

- [x] read data using SQL API read
- [x] read data using Pandas on Spark API reader, then convert to SQL DataFrame
- [x] read GeoPackage using pyspark_vector_files.gpkg.read_gpkg
- [x] read other vector files using  pyspark_vector_files
- [x] read metadata (this should be the same as in alpha v1
- [x] Ignore checking spatial data, add issue to pyspark_vector_files about spatial metadata
- [ ] Add tests
- [ ]  Add documentation

- Ignore categorisation
-  Ignore graph

**Comment by EFT-Defra** [comment]
Closing issue as pull request #136 is now on the board
