### ISSUE TITLE
Januaray To-Do

### ISSUE THREAD

**Issue by jpd-defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#207]
SDS Data Model To-do List:

graph.py + logger.py being worked on by Ed and James

Branches:

- [ ] #213

Issues:

- [ ] #208

Modules:

- [ ]   - table.py and _table.py (wait for issues checking to be completed then decide on what to keep)
- [ ]   - vector.py and _vector.py - (wait for issues checking to be completed then decide on what to keep)
- [ ] #209

Commenting (Private):

- [ ]   - constants.py - some constansts missing comments explaining what they are - add index
- [ ]   - _dataframe.py / dtype_nodata_value - add descriptive comment - why are some commented out? (L205)
- [ ]   - _dataframe.py / _GDAL_AT_LEAST_35, _GDAL_AT_LEAST_37 - add descriptive comment
- [ ]   - _dataframe.py / _get_minimum_dtype / - add comments explaining commented out else statements
- [ ]   - metadata.py / Metadata - add comments explaining why some parameters are commented out

  
 Documentation:

- [ ] #214
- [ ] #212
